### ISSUE TITLE
Sample about Images.jl

### ISSUE THREAD

**Issue by fonsp** [lukavdplas/pluto-notebooks#5]
@karlwessel do you have something?

We can also take material from https://mitmath.github.io/18S191/Fall20/hw1/

**Comment by karlwessel** [comment]
I'm not quite sure what the notebook should demonstrate. If the cell output is an "Image" (`RGB`-Array) it is displayed as an Image. It doesn't get much simpler :).

It may be nice to show how one can display it as an array instead, in case one is interested in the numerical values of the array.

**Comment by fonsp** [comment]
Haha good point

How do you show it as an array?

**Comment by karlwessel** [comment]
> Haha good point
> 
> How do you show it as an array?

I was hoping you would know :)

**Comment by karlwessel** [comment]
> How do you show it as an array?

`channelview(img)` is probably the best way to display the numerical values of the image array instead of the image.

**Comment by lukavdplas** [comment]
I think it's nice to have a demonstration, it would just be very short.

It's probably useful to show that you can include images in markdown as well. (A lot easier if you won't manipulate the image.)

**Comment by lukavdplas** [comment]
I created an notebook for this [here](https://github.com/lukavdplas/pluto-notebooks/blob/master/images.jl)

**Comment by karlwessel** [comment]
Nice!
I also needed to install `ImageMagick` to make the notebook work, otherwise the `load` method for images throws an error telling me to do so:
```
ArgumentError: Package ImageMagick not found in current path:

- Run `import Pkg; Pkg.add("ImageMagick")` to install the ImageMagick package.
```

**Comment by lukavdplas** [comment]
Thanks, I added that!

**Comment by karlwessel** [comment]
The notebook says showing images in Markdown works with remote and local images, but when I replace the remote URL for the pandas image with the path `pandas.jpg` of the downloaded local version nothing is displayed.

I also tried using the `Resource` type from `PlutoUI` and it doesn't show the image either.

But using `Images` and `load("pandas.png")` works.

Edit: Ok, it also works with `LocalResource` instead of `Resource`. Which makes sense :)
